apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: eu.gcr.io/adidas-zaragoza/HOSTNAME-server
        ports:
        - containerPort: 8080
